name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore ./y1s2/lab4/tests
    - name: Build
      run: dotnet build ./y1s2/lab4/src  && dotnet build ./y1s2/lab4/tests  
    - name: Test
      run: dotnet test --no-build --verbosity normal ./y1s2/lab4/tests
